import { defineKind } from '../src/shared/kinds.ts';

/**
 * An AI-generated picture of a standard dish, shown only where no real photo of that dish at
 * that place exists, and always labeled. Agents generate and upload them as work items; the
 * Worker itself calls no image model.
 */
export default defineKind({
  kind: 'illustration',
  title: { en: 'AI illustration', zh: 'AI 示意图' },
  noun: { en: { one: 'illustration', other: 'illustrations' }, zh: '张示意图' },
  fields: {
    dish: { type: 'text', max: 40, required: true, label: { en: 'Dish', zh: '菜名' }, help: 'The standard dish name the work item gives, exactly.' },
    model: { type: 'text', max: 60, required: true, label: { en: 'Model', zh: '生成模型' }, help: 'The image model you used, e.g. "gpt-image-1".' },
    prompt: { type: 'text', max: 2000, required: true, label: { en: 'Prompt', zh: '提示词' }, help: 'The prompt you gave the model, word for word.' },
    width: { type: 'number', server: true, label: { en: 'Width', zh: '宽' } },
    height: { type: 'number', server: true, label: { en: 'Height', zh: '高' } },
  },
  identity: ['dish'],
  provenance: 'upload',
  submit: 'agent-uploads',
  updatable: false,
  recheckAfterDays: null,
  pendingCap: { start: 5, max: 50 },
  example: { data: { dish: '虾饺', model: 'gpt-image-1', prompt: 'Realistic food photograph of har gow (虾饺)...' }, source_url: '', evidence: '' },
  scope: {
    in: 'One picture per standard dish that places in this dataset serve, generated by you with an image model from the prompt the work item gives.',
    out: 'Photos from the web or real photos you edited; pictures with text, letters, logos, watermarks, people or hands.',
  },
  sourceHints: [],
  maintainerChecks: [
    'It shows the dish the work item describes, as it is usually served.',
    'It looks like a realistic food photograph of one serving.',
    'No text, letters, logos, watermarks, people or hands.',
    "It is generated, not a real photo copied from the web (a watermark, a restaurant's branded plates or camera noise give that away).",
  ],
  display: ['dish'],
});
